#cloud-config
packages:
  - qemu-guest-agent
apt_update: true
apt_upgrade: true
ntp:
  ntp_client: auto
  enabled: true
package_update: true
package_upgrade: true
users:
  - default
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${var.ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    - timedatectl set-timezone Europe/Berlin
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/cloud-config.done